### ISSUE TITLE
FR: Pin the reference pop-up window to the page

### ISSUE THREAD

**Issue by dinogrgic1** [clippydsdone/clippy-frontend#40] opened 2022-11-08 18:53 UTC

**Comment by nsm18002** [comment] 2022-12-07 17:27
2022-12-04 18:00 - 21:00 3h, Tried to create a class for the viewer so we could easily instantiate as many viewers as we want. Lots of strange errors; suspecting it has to do with internal names of pdfViewer/linkService/eventBus using the same internal variable names for all instances and/or multiple viewers sharing the same <div>.

2022-12-05 18:00 - 21:00 3h, Figured out the problem is that pdfViewers and linkServices need to be on document/window-level, placing them in a superstructure or class causes them to be "undefined", I'm assuming some internal workings is hardcoded to lookup "document.pdfViewer". This can be resolved by dynamically instantiating variables using "window["pdfViewer619"] = new Global.app.pdfViewerConstructor();" "window["linkService619"] = new Global.app.pdfLinkService.constructor();".
New problem is pdfViewer.setDocument() is async and does a lot of async stuff inside hooking up references, need to figure out a way to wait for it to load before attempting linkService.goToDestination() as the destinations hasn't loaded by the time it gets called.

2022-12-06 16:00 - 19:00 3h, I can hijack the eventbus to update a ready flag when pdfViewer and linkService finish the setDocument() functions, still sometimes slips up and displays incorrectly. Suspecting that the services pdfScriptingManager & findController (called from PDFViewer.setDocument()) are also needed to be fully loaded to work properly, I cannot however get them to trigger an evenBus dispatch like you can with pdfViewer & linkService, they must use some other bus.

2022-12-06 20:00 - 23:00 3h, Expanded PopupViewer class, added event listeners, trying to come up with an implementation that isn't complete spaghetti.

2022-12-07 09:00 - 12:00 3h, Class based popupViewer works as intended, we can open as many popup windows as we want, they do however not scroll when the page is scrolled and is placed based on screen coordinates, getting it to scroll has proven exceedingly difficult but was resolved by making the popups themselves moveable FR7.

**Comment by nsm18002** [comment] 2022-12-12 17:21
2022-12-12 15:00 - 18:00, 3h, Bug fixes and feature changes requested by Branimir.

**Closed** 2022-12-12 20:09 UTC
