### ISSUE TITLE
FR: List of references in the sidebar

### ISSUE THREAD

**Issue by dunja274** [clippydsdone/clippy-frontend#26] opened 2022-11-01 20:39 UTC
Side panel contains list of all the references in the PDF. Click on the reference in the side panel opens the preview of the reference (similar to hover over pop-up window). 

Requested by: Sponsor

**Comment by branimir1999** [comment] 2022-11-25 15:07
- [ ] Size: I have issues dynamically resizing it. The way the resizing works in the pdf.js is that there's a listener for UI changes and when it detects that you're actually moving the sidebar, it calculates and manually adds a height and width value for each element. There's no inheritance whatsoever, just manual fixed input of dimensions. However, I have found out that the Container part of the viewer is responsible for how much of the document we see. A solution to this that I can think of is adding our HTML element into the queue of the rendering, but that requires tampering with the pdf.js which I would rather avoid.
- [ ] Clicking references in our sidebar panel: Currently, PDF.js listens to all mouse clicks, and if it figures out you're clicking a `<a href>` element, it will implicitly (without an explicit listener attached to the `<a href>` element) move the main document to the reference. I currently don't have a lead on how to make the listener ignore links in our sidebar panel.
- [ ] One or multiple viewers: my original idea is to have a snapshot of each reference underneath the reference (note the arrows next to the reference), but the snapshot idea turned out terrible in practice. The idea is terrible because it is extremely rigid and nonflexible (impossible to predict size and position of reference in paper and unable to make any changes for either scale or position). So I got an idea to have a single reference (pre)viewer and once you click on another reference, it moves the (pre)viewer to that reference and puts the viewer underneath the reference. The issue is, unless want to bloat the browser memory, we can only preview one reference at a time. That might be a serious drawback.
- [ ] Reference link name: Currently, I did a bit of my own parsing as a placeholder measure, but it's low quality. I believe the information about the thing the reference is referencing is impossible to get easily via viewer.js, I believe it's embedded information within the pdf file itself. I might need help deciphering this issue.
- [ ] Scaling (zoom-in): Currently, the scaling is set to 100%. I intend on adding buttons to allow the user to zoom in or out in the preview. Later, I would like to add zoom-in and zoom-out with mouse scroll but only when you hover over the preview.

**Closed** 2022-12-12 21:57 UTC
Labels: feature
